language: generic
sudo: required
servies:
- docker
before_install:
- docker build -t mehul2205/multi-react-test -f ./client/Dockerfile.dev ./client
script:
- docker run -e CI=true mehul2205/multi-react-test npm run test
after_success:
- docker build -t mehul2205/multi-client ./client
- docker build -t mehul2205/multi-nginx ./nginx
- docker build -t mehul2205/multi-server ./server
- docker build -t mehul2205/multi-worker ./worker
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
- docker push mehul2205/multi-client
- docker push mehul2205/multi-nginx
- docker push mehul2205/multi-server
- docker push mehul2205/multi-worker
deploy:
  provider: heroku
  api_key:
    secure: j41MNPlX7pqe5WB0RweAHcgfQWplkcjGesN+s5qcfQpn755ObY4ZrFcqeG4rG7a2rOtu7bzl71e5GlVAkQQ50qGbd5qQLlLVAx7lXc719XqZ76NGSXaV/6XBAOY1P/BZpA+QPfEHwq7cxUW1XBPeBgueNnzFyDoT4wss0LcslPKnqDX+VUoaG2oDIYsm+SndZ4pKuXE/QVyVNO48azJQibZDOnWXHUvYgJ4+uDDmsajy5ysSxg9C+lKEFDgR2Oy64p2aJYWJZjEFen0g5JsYwZjFB7gYrAspRZ0NsDTSyrId/zpuLGOEsjuR5jtDLGgSxftISvLt36xF90hHRaRbT/r8sGai4Hjt2hqvf3bGCfzwSOBFisy9sGF7d/vS41MQP4cgwdyvZNVctzF82bMWrnf1E0/OxLKrsoBDsNLbguGt9GIFCvKmTs6ax156ogLCboK+R7pw+yt9aph2Yv+XHI8sKdvbtfq9tiXdO3v5NQ8FkHCZb7wk3d59kymOz2Dsi5LnTHFivXk3F2LQzGd8FJyBOj8MUtYaHNakGlex+8cqAngRPRqDOSdaLXNRKGNhhCyzvG8PiRlL7YH9bLsu/hbh5UQXdGTm58ZOcDX+4fjgWu0joEljOhvYoou2B/q4Nse06kxz19u5dZzqniiviXgShzUPgoWrFfmlSv7YJLY=
  app: mehul2205-multi-container
  skip_cleanup: true
  on:
    branch: master
